name: Test WARM

on: push

jobs:
  build:
    name: build

    runs-on: ubuntu-latest
    
    steps:
    - name: installing llvm
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    - name: building wasi-libc
      run: |
        git clone https://github.com/WebAssembly/wasi-libc.git
        cd wasi-libc
        make WASM_CC=/usr/bin/clang WASM_AR=/usr/bin/llvm-ar WASM_NM=/usr/bin/llvm-nm
    - name: running script
      run: |
        cd ..
        ./make.sh clang "--sysroot=./wasi-libc/sysroot -O2 -flto" llvm-ar
